In [2]:
print('Hello! Its my 9th home work like exam :)')

Hello! Its my 9th home work like exam :)


In [8]:
#b. Создайте массив из 10 нулей
import numpy as np
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
#c. Создать массив из 10 единиц
arr = np.ones(10) 
print(arr)  

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [74]:
#d. Создать массив из 10 пятерок
arr = np.arange(0,10)
arr[:] = 5
print(arr)
x = len(arr)
print('этот массив состоит из', x, 'пятерок')

[5 5 5 5 5 5 5 5 5 5]
этот массив состоит из 10 пятерок


In [27]:
#e. Создать массив из целых чисел от 10 до 50
arr = np.arange (10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [29]:
#f. Создать массив из четных чисел от 10 до 50
arr = np.arange (10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [36]:
#Создать матрицу 3х3 с числами от 0 до 8
arr = np.arange(0,9)
arr1 = arr.reshape(3,3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
#h. Создать единичную матрицу 3x3
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [49]:
#i. Используйте NumPy для генерации случайного числа от 0 до 1
arr = np.random.rand()
print(arr)

0.2623179416372544


In [56]:
#j. Используйте NumPy для генерации массива из 25 случайных чисел, взятых из стандартного нормального распределения
arr = np.random.randint(0,100,25)
print(arr)
x = len(arr)
print('получилось', x, 'случайных чисел')

[80  0  8 12 69 21 51 78 78  9 38 26 84 93 70 14 85 98 24 99 94 40 74 74
 81]
получилось 25 случайных чисел


In [47]:
from numpy.core.fromnumeric import reshape
#k. Создайте следующую матрицу используя функции библиотеки NumPy
arr = np.linspace(0.01,1,100).reshape(10,10)
print(arr)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [66]:
#l. Дана стартовая матрица (обязательно запустите код ниже в вашем решении!). Эта матрица будет использоваться в последующих задачах
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5) 
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [88]:
#Необходимо написать код, который вернет следующую матрицу из стартовой:
mat = np.arange(1,26).reshape(5,5)
mat1 = mat[2:,1:]
print(mat1)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [95]:
#m. Написать код обращения к элементу который вернет значение 20 из стартовой матрицы задачи l.
mat = np.arange(1,26).reshape(5,5)
num = np.array(mat)
print(num[3][4])

20


In [94]:
#n.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
mat = np.arange(1,26).reshape(5,5)
mat1 = mat[0:3,1].reshape(3,1)
print(mat1)

[[ 2]
 [ 7]
 [12]]


In [97]:
#o. Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
mat = np.arange(1,26).reshape(5,5)
mat1 = mat[4,:]
print(mat1)

[21 22 23 24 25]


In [10]:
#p. Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
mat = np.arange(1,26).reshape(5,5)
mat1 = mat[3:,:]
print(mat1)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [26]:
#q. Получить сумму всех значений в стартовой матрице mat
mat = np.arange(1,26).reshape(5,5)
num = np.sum(mat)
print(f'Сумма всех элементов матрицы  = {num}')    #f-строка  - форматирвоание. позволяет совместно с {} писать полное предложение без запятых и пробелов

Сумма всех элементов матрицы  = 325


In [27]:
  #r. Получить стандартное отклонение в стартовой матрице mat
mat = np.arange(1,26).reshape(5,5)
num = np.std(mat)
print(f'Стандартное отклонение в мартице = {num}')

Стандартное отклонение в мартице = 7.211102550927978


In [28]:
#s. Получить сумму значений в колонках в стартовой матрице mat
mat = np.arange(1,26).reshape(5,5)
total_0_axis = np.sum(mat, axis=0) 
print(f'Сумма всех элементов по столбцам матрицы  = {total_0_axis}') 
total_1_axis = np.sum(mat, axis=1) 
print(f'Сумма всех элементов по строкам матрицы {total_1_axis}')


Сумма всех элементов по столбцам матрицы  = [55 60 65 70 75]
Сумма всех элементов по строкам матрицы [ 15  40  65  90 115]
